CC      ?= g++
CFLAGS  += -g
RM      ?= rm -f


default: all

all:  emu_60_2_2116

emu_60_2_2116: emu_60_2_2116.c
	$(CC) $(CFLAGS) -o emu_60_2_2116 emu_60_2_2116.c

clean:
	$(RM) emu_60_2_2116 emu_60_2_2116.o



